
import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";
import apiClient from "@/api/apiClient";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft, ArrowRight, Loader2, Sparkles } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";
import PromptEditor from "../components/prompts/PromptEditor";

export default function PromptReview() {
  const navigate = useNavigate();
  const urlParams = new URLSearchParams(window.location.search);
  const companyId = urlParams.get('companyId');
  const topics = urlParams.get('topics')?.split(',') || [];

  const [promptsByTopic, setPromptsByTopic] = useState({});
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasGenerated, setHasGenerated] = useState(false);
  const [maxPrompts, setMaxPrompts] = useState(null); // Start as null to wait for fetch

  const { data: company, isLoading } = useQuery({
    queryKey: ['company', companyId],
    queryFn: async () => {
      const companies = await apiClient.entities.Company.filter({ id: companyId });
      return companies[0];
    },
    enabled: !!companyId,
  });

  // Fetch max prompts limit from backend
  useEffect(() => {
    const fetchMaxPrompts = async () => {
      try {
        const response = await apiClient.functions.invoke('getMaxPrompts');
        setMaxPrompts(response.data.maxPrompts || 20);
      } catch (error) {
        console.error('Error fetching max prompts:', error);
        setMaxPrompts(20); // Fallback to 20 if fetch fails
      }
    };
    fetchMaxPrompts();
  }, []);

  useEffect(() => {
    const sessionCompanyId = sessionStorage.getItem('companyId');
    if (companyId && sessionCompanyId && companyId !== sessionCompanyId) {
      console.warn('Unauthorized access attempt to different company');
      navigate(createPageUrl("Start"));
    }
  }, [companyId, navigate]);

  // Only generate prompts when we have company, topics, maxPrompts, and haven't generated yet
  useEffect(() => {
    if (company && topics.length > 0 && maxPrompts !== null && !hasGenerated) {
      generateAllPrompts();
    }
  }, [company, topics, maxPrompts, hasGenerated]);

  const generateAllPrompts = async () => {
    setIsGenerating(true);
    const newPromptsByTopic = {};

    // Use the fetched or defaulted maxPrompts for total generation count
    const totalAutoGeneratedPrompts = maxPrompts;
    const promptsPerTopicBase = Math.floor(totalAutoGeneratedPrompts / topics.length);
    let remainder = totalAutoGeneratedPrompts % topics.length;

    for (let i = 0; i < topics.length; i++) {
      const topic = topics[i];
      // Ensure count is at least 1, even if maxPrompts is very low or topics are many
      const count = Math.max(1, promptsPerTopicBase + (i < remainder ? 1 : 0));
      console.log("Generating", count, "prompts for", company.name, "on topic:", topic);
      const isGeneralPresence = topic === 'General Company Presence';
      const products = isGeneralPresence ? (company.products || []) : null;

      const result = await apiClient.functions.invoke('generatePrompts', {
        companyName: company.name,
        topic,
        count,
        products: products
      });
      newPromptsByTopic[topic] = result.data.prompts || [];
    }

    setPromptsByTopic(newPromptsByTopic);
    setHasGenerated(true);
    setIsGenerating(false);
  };

  const handleStartAnalysis = () => {
    console.log('Starting analysis with prompts:', promptsByTopic);

    // Store prompts in sessionStorage instead of URL
    sessionStorage.setItem('analysisPrompts', JSON.stringify(promptsByTopic));

    // Navigate with minimal URL params
    navigate(createPageUrl("RunAnalysis") + `?companyId=${companyId}&topics=${encodeURIComponent(topics.join(','))}`);
  };

  const handlePromptChange = (topic, newPrompts) => {
    console.log(`Updating prompts for topic "${topic}":`, newPrompts);
    setPromptsByTopic(prev => ({
      ...prev,
      [topic]: newPrompts
    }));
  };

  const totalPrompts = Object.values(promptsByTopic).reduce((sum, prompts) => sum + prompts.length, 0);

  if (isLoading || maxPrompts === null) {
    return (
      <div className="min-h-screen p-4 md:p-8 bg-[#f7f3f0]">
        <div className="max-w-6xl mx-auto">
          <Skeleton className="h-12 w-64 mb-8" />
          <Card>
            <CardContent className="pt-6">
              <div className="space-y-4">
                {[1, 2, 3].map(i => (
                  <Skeleton key={i} className="h-16 w-full" />
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-4 md:p-8 bg-[#f7f3f0]">
      <div className="max-w-6xl mx-auto">
        <Button
          variant="ghost"
          onClick={() => navigate(createPageUrl("TopicSelection") + `?companyId=${companyId}`)}
          className="mb-6"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back
        </Button>

        <div className="mb-8 flex items-center justify-between">
          <div>
            <h1 className="text-4xl font-bold text-[#344547] mb-2">
              Review & Edit Prompts
            </h1>
            <p className="text-lg text-slate-600">
              We've generated customer questions for {company?.name}. Review and customize them before running the analysis.
            </p>
          </div>
          <Button
            onClick={() => {
              setHasGenerated(false); // Reset hasGenerated to re-trigger prompt generation
            }}
            disabled={isGenerating}
            variant="outline"
            className="flex items-center gap-2"
          >
            {isGenerating ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Sparkles className="w-4 h-4" />
            )}
            Regenerate Prompts
          </Button>
        </div>

        {isGenerating ? (
          <Card className="border-0 shadow-xl backdrop-blur-xl bg-white">
            <CardContent className="py-16 text-center">
              <Loader2 className="w-12 h-12 animate-spin text-[#df1d29] mx-auto mb-4" />
              <p className="text-lg text-slate-600">Generating prompts...</p>
              <p className="text-sm text-slate-500 mt-2">This will take a moment</p>
            </CardContent>
          </Card>
        ) : (
          <>
            <div className="space-y-6 mb-8">
              {topics.map(topic => (
                <PromptEditor
                  key={topic}
                  topic={topic}
                  prompts={promptsByTopic[topic] || []}
                  // Calculate available slots for this specific topic based on overall max and other topics' current prompts
                  maxPrompts={maxPrompts - (totalPrompts - (promptsByTopic[topic] || []).length)}
                  onChange={(newPrompts) => handlePromptChange(topic, newPrompts)}
                />
              ))}
            </div>

            <Card className="border-0 shadow-xl backdrop-blur-xl bg-white mb-6">
              <CardContent className="py-6">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-gradient-to-br from-[#344547] to-[#2a3638] rounded-lg flex items-center justify-center">
                    <Sparkles className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <p className="font-semibold text-[#344547]">
                      {totalPrompts} of {maxPrompts} prompts ready
                    </p>
                    <p className="text-sm text-slate-600">
                      Testing across ChatGPT, Gemini, Perplexity, and Google
                    </p>
                  </div>
                </div>
                <div className="mt-6 flex justify-end">
                  <Button
                    size="lg"
                    onClick={handleStartAnalysis}
                    disabled={totalPrompts === 0}
                    className="bg-[#df1d29] hover:bg-[#c51923] text-white shadow-lg shadow-red-500/30 text-lg px-8"
                  >
                    Run Analysis
                    <ArrowRight className="w-5 h-5 ml-2" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          </>
        )}
      </div>
    </div>
  );
}
